name: Run WhatsApp Bot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Menggunakan Node.js versi 20

    - name: Install dependencies
      run: npm install

    - name: Run bot
      run: npm start  # Sesuaikan dengan perintah untuk menjalankan bot Anda
